name: trigger jenkins job

# or add https://jenkins.mohamed-mourabit.com/github-webhook
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  JOB_NAME: 'infoacademie-api'
  TOKEN: '1190ece073ad727d92826064019aec2340'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://jenkins.mohamed-mourabit.com"
        user: "admin"
        token: ${{ env.TOKEN }}
        job: "${{ env.JOB_NAME }}"
